---
  - hosts: ans-app-group
    become: true
    tasks:
    - name: install Epel and webtatic repos
      yum: name={{item}} state=present
      with_items:
        - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        - epel-release

    - name: install Soft Pack
      yum: name={{item}} state=present
      with_items:
        - httpd
        - vim
        - git
        - nodejs
        
    - name: Install php Pack
      yum: name={{item}} state=present
      with_items:
        - php70w
        - php70w-opcache
        - php70w-mbstring
        - php70w-xml

    - name: restart httpd
      systemd:
        name: httpd
        state: restarted
        enabled: yes

    - name: Get kwicktchat
      git:
        repo: https://github.com/Maftouhou/kwicktchat.git
        dest: /var/www/html/kwicktchat/
      notify: restart httpd

    - name: Get eLycee
      git:
        repo: https://github.com/Maftouhou/elycee.git
        dest: /var/www/html/elycee/
      notify: remove_composer_lock

    - name: Download Composer 
      get_url: 
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer-setup.php

    - name: set privilege on app folder
      file:
        path: '{{item}}'
        owner: apache
        group: apache
        recurse: yes
      with_items: 
        - /var/www/html/elycee/bootstrap
        - /var/www/html/elycee/storage

    - name: Configure App env
      shell: cp /var/www/html/elycee/.env.exemple /var/www/html/elycee/.env

    - name: Install Composer 
      shell: php composer-setup.php
      args:
        chdir: /usr/local/bin/
    
    - name: rename_composer
      shell: mv composer.phar composer
      args:
        chdir: /usr/local/bin/

    #- name: remove composer.lock on projet
    #  file: 
    #    path: /var/www/html/elycee/composer.lock
    #    state: absent

    #- name: Installing Composer Dependancies
    #  composer:
    #    command: install
    #    working_dir: /var/www/html/elycee/

    - name: restart httpd alone
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    
    - name: Install Bower
      npm:
        name: bower
        global: yes

   # - name: Install Node packages
   #   npm:
   #     path: '{{item}}'
   #   with_items: 
   #     - /var/www/html/elycee/
   #     - /var/www/html/elycee/public/

   # - name: Install Bower packages
   #   bower:
   #     path: /var/www/html/elycee/public/

    handlers: 
    - name: restart httpd
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
        
    - name: remove_composer_lock
      file:
        path: /var/www/html/elycee/composer.lock
        state: absent 
        
