---
  - hosts: ans-db-group
    become: true
    tasks:
    
    ##################################
    # Manage Mysql users
    # --------------------------------
    - name: Removing anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Create Mysql user
      mysql_user: 
        host: '{{item}}'
        name: ansible
        password: ansible
        priv: '*.*:ALL,GRANT'
        state: present
      with_items:
        - localhost
        - '%'

  #######################################
  # Move database from app-svr to db-svr
  # -------------------------------------
  - hosts: ans-app-group
    become: true
    tasks:
    - name: get database from app-svr project folder
      fetch: 
        src: /var/www/html/Blog_PHP/db_blogphp.sql
        dest: /tmp/ansible/db_blogphp.sql 

  - hosts: ans-db-group
    become: true
    tasks:
    - name: Create destination folder for database
      file: 
        path: '/tmp/{{item}}'
        state: directory
        mode: 0755
      with_items:
        - ansible
        - db_ansible

    - name: send database to db-svr 
      copy: 
        src: /tmp/ansible/db_blogphp.sql
        dest: /tmp/ansible/db_blogphp.sql


  ######################################
  # Manage Mysql database
  # ------------------------------------
  - hosts: ans-db-group
    become: true
    tasks:

    - name: Prepare database to import
      shell: find -type f -name db_blogphp.sql | xargs cp -u -t /tmp/db_ansible/
      args:
        chdir: /tmp/ansible/

    - name: Create database
      mysql_db: 
        name: db_blogphp
        state: present

    - name: Import Mysql database
      mysql_db:
        state: import
        name: db_blogphp
        target: /tmp/db_ansible/db_blogphp.sql
        
    - name: Start Mysql server
      systemd: 
        state: started
        name: mariadb

