---
## Calling all playbooks
# ---------------------------------------
- import_playbook: WebServer/SoftwareInstall.yml
- import_playbook: DatabaseServer/SoftwareInstall.yml
- import_playbook: ApplicationConfiguration/ProjectInstall.yml
- import_playbook: databaseConfiguration/databaseConfiguration.yml
