---
  - hosts: ans-app-group
    become: true
    tasks:
    - name: install Soft Pack
      yum: name={{item}} state=present
      with_items:
        - httpd
        - vim
        - git
        - nodejs
        - rsync
