---
# tasks file for httpd
## ----------------------------------------- 
# Install Composer process
# ------------------------------------------
- name: install Epel and webtatic repos
  yum: name={{item}} state=present
  with_items:
    - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    - epel-release

- name: install Soft Pack
  yum: 
    name: '{{item}}' 
    state: present
  with_items:
    - httpd
    - vim
    - git
    - nodejs
    
- name: Install php Pack
  yum: 
    name: '{{item}}' 
    state: present
  with_items:
    - php70w
    - php70w-opcache
    - php70w-mbstring
    - php70w-xml
    - php70w-mysql


- name: restart httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
    
- include: Inc.httpd.conf.yml
