---
# tasks file for httpd
## ----------------------------------------- 
# Install Composer process
# ------------------------------------------
- name: install Epel and webtatic repos
  yum: name={{item}} state=present
  with_items:
    - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    - epel-release

- name: install Soft Pack
  yum: 
    name: '{{item}}' 
    state: present
  with_items:
    - httpd
    - vim
    - git
    - nodejs
    
- name: Install php Pack
  yum: 
    name: '{{item}}' 
    state: present
  with_items:
    - php70w
    - php70w-opcache
    - php70w-mbstring
    - php70w-xml
    - php70w-mysql

- name: Httpd.conf access right
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
  with_items:
    - { regexp: '^\s+\s+(AllowOverride)\s+(none|None)\s*$', line: '    AllowOverride all' }
    - { regexp: '^\s+\s+(AllowOverride)\s+(none|None)\s*$', line: '    AllowOverride all' }
    - { regexp: '^\s+\s+(AllowOverride)\s+(none|None)\s*$', line: '    AllowOverride all' }
    - { regexp: '^\s+\s+(AllowOverride)\s+(none|None)\s*$', line: '    AllowOverride all' }

- name: restart httpd
  systemd:
    name: httpd
    state: started
    enabled: yes

## ----------------------------------------- 
# Install Composer process
# ------------------------------------------
- name: Download Composer 
  get_url: 
    url: https://getcomposer.org/installer
    dest: /usr/local/bin/composer-setup.php

- name: Install Composer 
  shell: php composer-setup.php
  args:
    chdir: /usr/local/bin/

- name: rename_composer
  shell: mv composer.phar composer
  args:
    chdir: /usr/local/bin/

- name: restart httpd alone
  systemd:
    name: httpd
    state: restarted
    enabled: yes

## ----------------------------------------- 
# Install Composer process
# ------------------------------------------
#- name: Install Bower
#  npm:
#    name: bower
#    global: yes
