---
  - hosts: ans-app-group
    become: true
    tasks:

    #- name: Get kwicktchat
    #  git:
    #    repo: https://github.com/Maftouhou/kwicktchat.git
    #   dest: /var/www/html/kwicktchat/
    # notify: restart httpd

    - name: Get Blog_PHP
      git:
        repo: https://github.com/Maftouhou/Blog_php.git
        dest: /var/www/html/Blog_PHP/
      #notify: remove_composer_lock

    - name: set privilege on app folder
      file:
        path: '{{item}}'
        owner: apache
        group: apache
        recurse: yes
      with_items: 
        - /var/www/html/Blog_PHP/bootstrap
        - /var/www/html/Blog_PHP/storage

    - name: Creating App env file
      shell: cp /var/www/html/Blog_PHP/.env.example /var/www/html/Blog_PHP/.env

    - include: EnvirnementConfiguration.yml

    #- name: remove composer.lock on projet
    #  file: 
    #    path: /var/www/html/Blog_PHP/composer.lock
    #    state: absent

    #- name: Cleaning composer cache
    #  shell: /usr/local/bin/composer clearcache

    - name: Installing Composer Dependancies
      composer:
        command: install
        working_dir: /var/www/html/Blog_PHP/

    - name: restart httpd alone
      systemd:
        name: httpd
        state: restarted
        enabled: yes

    - name: Generate Application key
      shell: php artisan key:generate
      args:
        chdir: /var/www/html/Blog_PHP/

    handlers: 
    - name: restart httpd
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
        
    #- name: remove_composer_lock
    #  file:
    #    path: /var/www/html/Blog_PHP/composer.lock
    #    state: absent 
        
